### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by agebhar1** [innovate-technologies/Dispatch#6]
> Dispatch is a low level orhectration tool to distribyte SystemD units via etcd.

`s/orhectration/orchestration` :wink:

**Comment by meyskens** [comment]
Thank you! My brain reads over this kind of stuff.... will fix it as soon as I can

**Comment by agebhar1** [comment]
No worries - there are 3 typos at the end :wink: 

Fixed it for you via PR #7
